openapi: 3.0.0
info:
  title: Event Analyzer API
  description: API for inspecting the Kafka message queue and generating statistics on events.
  contact:
    email: support@gametracker.com
  version: 1.0.0
servers:
  - url: /
paths:
  /events/player:
    get:
      summary: Retrieve a specific player event from Kafka
      description: Returns a player event at the specified index in the Kafka queue.
      operationId: app.get_player_event
      parameters:
        - name: index
          in: query
          description: Index of the player event in the Kafka queue
          required: true
          schema:
            type: integer
            example: 5
      responses:
        "200":
          description: Player event retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerActivityEvent'
        "404":
          description: Event not found at the given index

  /events/server:
    get:
      summary: Retrieve a specific server event from Kafka
      description: Returns a server event at the specified index in the Kafka queue.
      operationId: app.get_server_event
      parameters:
        - name: index
          in: query
          description: Index of the server event in the Kafka queue
          required: true
          schema:
            type: integer
            example: 3
      responses:
        "200":
          description: Server event retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerPerformanceEvent'
        "404":
          description: Event not found at the given index

  /stats:
    get:
      summary: Retrieve event statistics
      description: Returns statistics about the number of events in the Kafka queue.
      operationId: app.get_event_statistics
      responses:
        "200":
          description: Event statistics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventStatistics'

components:
  schemas:
    PlayerActivityEvent:
      required:
        - action
        - player_id
        - score
        - server_id
        - timestamp
        - trace_id
      type: array
      properties:
        player_id:
          type: string
          description: Unique identifier of the player
          example: "12345"
        server_id:
          type: string
          description: Unique identifier of the server
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        action:
          type: string
          description: Action performed by the player
          example: "killed_monster"
        score:
          type: integer
          description: Score earned by the player
          example: 100
        timestamp:
          type: string
          format: date-time
          description: Time the event was recorded
          example: "2025-01-09T13:15:30"
        trace_id:
          type: string
          description: Unique trace identifier for tracking
          example: "abc123-def456-ghi789"

    ServerPerformanceEvent:
      required:
        - cpu_usage
        - memory_usage
        - server_id
        - timestamp
        - uptime
        - trace_id
      type: array
      properties:
        server_id:
          type: string
          description: Unique identifier of the server
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        uptime:
          type: integer
          description: Server uptime in seconds
          example: 7200
        cpu_usage:
          type: number
          format: float
          description: CPU usage percentage
          example: 78.5
        memory_usage:
          type: number
          format: float
          description: Memory usage percentage
          example: 63.2
        timestamp:
          type: string
          format: date-time
          description: Time the event was recorded
          example: "2025-01-09T13:15:30"
        trace_id:
          type: string
          description: Unique trace identifier for tracking
          example: "xyz987-mno654-pqr321"

    EventStatistics:
      type: object
      description: Statistics on the number of events in the Kafka queue
      additionalProperties:
        type: integer
      example:
        num_player_events: 189
        num_server_events: 213
