FROM nginx:latest
COPY dashboard.html /usr/share/nginx/html/index.html
COPY dashboard.js /usr/share/nginx/html/dashboard.js
COPY your-logo.png /usr/share/nginx/html/your-logo.png  # Replace with your actual logo image
