openapi: 3.0.0
info:
  description: This API provides event anomalies
  version: "1.0.0"
  title: Anomaly API
  contact:
    email: awong540@my.bcit.ca

paths:
  /update:
    put:
      summary: Update the anomalies datastore
      operationId: app.update_anomalies
      description: Updates the anomalies datastore from the Kafka queue
      responses:
        '201':
          description: Successfully updated the anomalies datastore
          content:
            application/json:
              schema:
                type: object
                properties:
                  anomalies_count:
                    type: integer
                    example: 5
  /anomalies:
    get:
      summary: Gets the anomalies
      operationId: app.get_anomalies
      description: Gets the list of event anomalies
      parameters:
        - name: event_type
          in: query
          description: Filter by event type (EVENT1, EVENT2) - shows all anomalies if not provided
          schema:
            type: string
            example: PlayerActivityEvent
      responses:
        '200':
          description: Successfully returned a non-empty list of anomalies of the given event type
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Anomaly'
        '204':
          description: No anomalies found for the given event type
        '400':
          description: Invalid Event Type, must be EVENT1 or EVENT2 # CHANGE THIS
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: The anomalies datastore is missing or corrupted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    Anomaly:
      required:
      - id
      - trace_id
      - event_type
      - description
      properties:
        id:
          type: string
          description: Unique identifier of the event
          example: "A1234"
        trace_id:
          type: string
          description: Trace ID of the event
          example: "T5678"
        event_type:
          type: string
          description: Type of the event (`PlayerActivityEvent` or `ServerPerformanceEvent`)
          example: ServerPerformanceEvent
        description:
          type: string
          description: Description of the anomaly, including the value detected and the threshold exceeded
          example: "CPU usage detected: 99%; threshold: 90%"
      type: object